---
name: Verify PR

on:
  push:
    branches:
      - ci-testing*

  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: install python libs
        run: uv sync

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install
          echo "$GITHUB_WORKSPACE/node_modules/.bin" >> "$GITHUB_PATH"

      - name: Build the page
        run: |
          just generate
